[build]
  functions = "functions"
  publish = "ui/webapp"


[[redirects]]
  from = "/catalog/Authors"
  to = "/.netlify/functions/catalog/Authors"
  status = 200

[[redirects]]
  from = "/catalog/Books"
  to = "/.netlify/functions/catalog/Books"
  status = 200

[[redirects]]
  from = "/catalog/$metadata"
  to = "/.netlify/functions/catalog/$metadata"
  status = 200